// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gchat.proto

package gchat

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserContent struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ChatName             string   `protobuf:"bytes,3,opt,name=chatName,proto3" json:"chatName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserContent) Reset()         { *m = UserContent{} }
func (m *UserContent) String() string { return proto.CompactTextString(m) }
func (*UserContent) ProtoMessage()    {}
func (*UserContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_df1dce88d8f72ba5, []int{0}
}

func (m *UserContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserContent.Unmarshal(m, b)
}
func (m *UserContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserContent.Marshal(b, m, deterministic)
}
func (m *UserContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserContent.Merge(m, src)
}
func (m *UserContent) XXX_Size() int {
	return xxx_messageInfo_UserContent.Size(m)
}
func (m *UserContent) XXX_DiscardUnknown() {
	xxx_messageInfo_UserContent.DiscardUnknown(m)
}

var xxx_messageInfo_UserContent proto.InternalMessageInfo

func (m *UserContent) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserContent) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserContent) GetChatName() string {
	if m != nil {
		return m.ChatName
	}
	return ""
}

type ChatMessage struct {
	Sequence             int32    `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_df1dce88d8f72ba5, []int{1}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetSequence() int32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *ChatMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RegisterResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df1dce88d8f72ba5, []int{2}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df1dce88d8f72ba5, []int{3}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df1dce88d8f72ba5, []int{4}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func (m *LogoutResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type MessageResponse struct {
	Val                  bool     `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df1dce88d8f72ba5, []int{5}
}

func (m *MessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResponse.Unmarshal(m, b)
}
func (m *MessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResponse.Marshal(b, m, deterministic)
}
func (m *MessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResponse.Merge(m, src)
}
func (m *MessageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageResponse.Size(m)
}
func (m *MessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResponse proto.InternalMessageInfo

func (m *MessageResponse) GetVal() bool {
	if m != nil {
		return m.Val
	}
	return false
}

type Chats struct {
	ChatName             string   `protobuf:"bytes,1,opt,name=chatName,proto3" json:"chatName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chats) Reset()         { *m = Chats{} }
func (m *Chats) String() string { return proto.CompactTextString(m) }
func (*Chats) ProtoMessage()    {}
func (*Chats) Descriptor() ([]byte, []int) {
	return fileDescriptor_df1dce88d8f72ba5, []int{6}
}

func (m *Chats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chats.Unmarshal(m, b)
}
func (m *Chats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chats.Marshal(b, m, deterministic)
}
func (m *Chats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chats.Merge(m, src)
}
func (m *Chats) XXX_Size() int {
	return xxx_messageInfo_Chats.Size(m)
}
func (m *Chats) XXX_DiscardUnknown() {
	xxx_messageInfo_Chats.DiscardUnknown(m)
}

var xxx_messageInfo_Chats proto.InternalMessageInfo

func (m *Chats) GetChatName() string {
	if m != nil {
		return m.ChatName
	}
	return ""
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_df1dce88d8f72ba5, []int{7}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*UserContent)(nil), "gchat.UserContent")
	proto.RegisterType((*ChatMessage)(nil), "gchat.ChatMessage")
	proto.RegisterType((*RegisterResponse)(nil), "gchat.RegisterResponse")
	proto.RegisterType((*LoginResponse)(nil), "gchat.LoginResponse")
	proto.RegisterType((*LogoutResponse)(nil), "gchat.LogoutResponse")
	proto.RegisterType((*MessageResponse)(nil), "gchat.MessageResponse")
	proto.RegisterType((*Chats)(nil), "gchat.Chats")
	proto.RegisterType((*Response)(nil), "gchat.Response")
}

func init() { proto.RegisterFile("gchat.proto", fileDescriptor_df1dce88d8f72ba5) }

var fileDescriptor_df1dce88d8f72ba5 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xc1, 0x8e, 0xda, 0x30,
	0x10, 0x4d, 0x40, 0x81, 0x74, 0xd2, 0x02, 0xb2, 0x68, 0x1b, 0xe5, 0x54, 0x99, 0xb6, 0xe2, 0x52,
	0x54, 0x81, 0x38, 0x54, 0x95, 0x7a, 0xc9, 0xa1, 0x52, 0x45, 0x7b, 0x08, 0xea, 0x07, 0xb8, 0x61,
	0x14, 0xa2, 0x16, 0x9b, 0xda, 0x0e, 0xfb, 0xa9, 0xfb, 0x3b, 0x2b, 0xc7, 0x4e, 0x36, 0x20, 0x56,
	0x48, 0x7b, 0xf3, 0x9b, 0x79, 0xf3, 0x66, 0xe6, 0x8d, 0x0c, 0x51, 0x91, 0xef, 0x99, 0x5e, 0x1c,
	0xa5, 0xd0, 0x82, 0x04, 0x35, 0xa0, 0x0c, 0xa2, 0xdf, 0x0a, 0x65, 0x2a, 0xb8, 0x46, 0xae, 0x49,
	0x02, 0x61, 0xa5, 0x50, 0x72, 0x76, 0xc0, 0xd8, 0x7f, 0xe7, 0xcf, 0x5f, 0x64, 0x2d, 0x36, 0xb9,
	0x23, 0x53, 0xea, 0x4e, 0xc8, 0x5d, 0xdc, 0xb3, 0xb9, 0x06, 0x9b, 0x9c, 0x91, 0xfb, 0x65, 0xea,
	0xfa, 0x36, 0xd7, 0x60, 0x9a, 0x42, 0x94, 0xee, 0x99, 0xfe, 0x89, 0x4a, 0xb1, 0xa2, 0x96, 0x51,
	0xf8, 0xbf, 0x42, 0x9e, 0xdb, 0x16, 0x41, 0xd6, 0x62, 0x12, 0xc3, 0xf0, 0x60, 0x69, 0xae, 0x43,
	0x03, 0xe9, 0x1c, 0x26, 0x19, 0x16, 0xa5, 0xd2, 0x28, 0x33, 0x54, 0x47, 0xc1, 0x15, 0x92, 0x29,
	0x04, 0x5a, 0xfc, 0x45, 0xee, 0x26, 0xb5, 0x80, 0x7e, 0x80, 0x57, 0x1b, 0x51, 0x94, 0xfc, 0x06,
	0xed, 0x23, 0x8c, 0x36, 0xa2, 0x10, 0x95, 0xbe, 0xc1, 0x9b, 0xc1, 0xd8, 0x4d, 0xde, 0x12, 0x27,
	0xd0, 0x3f, 0xb1, 0x7f, 0x35, 0x2d, 0xcc, 0xcc, 0x93, 0xce, 0x20, 0x30, 0x2b, 0xaa, 0x33, 0x1f,
	0xfc, 0x0b, 0x1f, 0xde, 0x43, 0xd8, 0x4a, 0xc4, 0x30, 0x54, 0x55, 0x9e, 0xa3, 0x52, 0x4e, 0xa6,
	0x81, 0xcb, 0x1f, 0x86, 0x95, 0x63, 0x79, 0x42, 0x49, 0xbe, 0xc1, 0xc8, 0xbd, 0x1b, 0xf3, 0xc8,
	0xc2, 0xde, 0xb0, 0x63, 0x68, 0xf2, 0xc6, 0xc5, 0x2e, 0xc6, 0xa4, 0xde, 0xf2, 0xbe, 0x67, 0xad,
	0xdf, 0xa2, 0x3c, 0x95, 0x39, 0x92, 0x2f, 0x46, 0xdb, 0x9a, 0xd8, 0x2a, 0x75, 0xae, 0x9f, 0xbc,
	0x75, 0xb1, 0x4b, 0xa7, 0xa9, 0x47, 0x56, 0x10, 0xd4, 0xae, 0x5e, 0xad, 0x9b, 0xba, 0xd8, 0x99,
	0xef, 0xd4, 0x23, 0x6b, 0x18, 0x58, 0x8f, 0xaf, 0x56, 0xbd, 0x7e, 0xac, 0xea, 0x9c, 0x81, 0x7a,
	0xe4, 0x2b, 0x44, 0x5b, 0xe4, 0xbb, 0x67, 0xed, 0x4c, 0xd6, 0x10, 0x7e, 0x47, 0x6d, 0xaf, 0xf1,
	0xd4, 0x3e, 0xc9, 0xcb, 0x8e, 0xa4, 0xa2, 0xde, 0x67, 0x9f, 0x7c, 0x02, 0x48, 0x25, 0x32, 0x8d,
	0x26, 0x44, 0xce, 0xf2, 0xc9, 0xb8, 0x95, 0x69, 0xba, 0xfc, 0x19, 0xd4, 0x9f, 0x68, 0xf5, 0x10,
	0x00, 0x00, 0xff, 0xff, 0x29, 0x2a, 0xa9, 0x8e, 0x53, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReceiverClient is the client API for Receiver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReceiverClient interface {
	ReceiveMessage(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*MessageResponse, error)
}

type receiverClient struct {
	cc *grpc.ClientConn
}

func NewReceiverClient(cc *grpc.ClientConn) ReceiverClient {
	return &receiverClient{cc}
}

func (c *receiverClient) ReceiveMessage(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, "/gchat.Receiver/ReceiveMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReceiverServer is the server API for Receiver service.
type ReceiverServer interface {
	ReceiveMessage(context.Context, *ChatMessage) (*MessageResponse, error)
}

// UnimplementedReceiverServer can be embedded to have forward compatible implementations.
type UnimplementedReceiverServer struct {
}

func (*UnimplementedReceiverServer) ReceiveMessage(ctx context.Context, req *ChatMessage) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveMessage not implemented")
}

func RegisterReceiverServer(s *grpc.Server, srv ReceiverServer) {
	s.RegisterService(&_Receiver_serviceDesc, srv)
}

func _Receiver_ReceiveMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiverServer).ReceiveMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gchat.Receiver/ReceiveMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiverServer).ReceiveMessage(ctx, req.(*ChatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Receiver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gchat.Receiver",
	HandlerType: (*ReceiverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveMessage",
			Handler:    _Receiver_ReceiveMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gchat.proto",
}

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatServiceClient interface {
	Register(ctx context.Context, in *UserContent, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *UserContent, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *UserContent, opts ...grpc.CallOption) (*LogoutResponse, error)
	SendMessage(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*MessageResponse, error)
	GetChats(ctx context.Context, in *RegisterResponse, opts ...grpc.CallOption) (ChatService_GetChatsClient, error)
	CreateChat(ctx context.Context, in *Chats, opts ...grpc.CallOption) (*Response, error)
}

type chatServiceClient struct {
	cc *grpc.ClientConn
}

func NewChatServiceClient(cc *grpc.ClientConn) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) Register(ctx context.Context, in *UserContent, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/gchat.ChatService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) Login(ctx context.Context, in *UserContent, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/gchat.ChatService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) Logout(ctx context.Context, in *UserContent, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/gchat.ChatService/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SendMessage(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, "/gchat.ChatService/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetChats(ctx context.Context, in *RegisterResponse, opts ...grpc.CallOption) (ChatService_GetChatsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ChatService_serviceDesc.Streams[0], "/gchat.ChatService/GetChats", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceGetChatsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatService_GetChatsClient interface {
	Recv() (*Chats, error)
	grpc.ClientStream
}

type chatServiceGetChatsClient struct {
	grpc.ClientStream
}

func (x *chatServiceGetChatsClient) Recv() (*Chats, error) {
	m := new(Chats)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatServiceClient) CreateChat(ctx context.Context, in *Chats, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/gchat.ChatService/CreateChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
type ChatServiceServer interface {
	Register(context.Context, *UserContent) (*RegisterResponse, error)
	Login(context.Context, *UserContent) (*LoginResponse, error)
	Logout(context.Context, *UserContent) (*LogoutResponse, error)
	SendMessage(context.Context, *ChatMessage) (*MessageResponse, error)
	GetChats(*RegisterResponse, ChatService_GetChatsServer) error
	CreateChat(context.Context, *Chats) (*Response, error)
}

// UnimplementedChatServiceServer can be embedded to have forward compatible implementations.
type UnimplementedChatServiceServer struct {
}

func (*UnimplementedChatServiceServer) Register(ctx context.Context, req *UserContent) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedChatServiceServer) Login(ctx context.Context, req *UserContent) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedChatServiceServer) Logout(ctx context.Context, req *UserContent) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (*UnimplementedChatServiceServer) SendMessage(ctx context.Context, req *ChatMessage) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (*UnimplementedChatServiceServer) GetChats(req *RegisterResponse, srv ChatService_GetChatsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetChats not implemented")
}
func (*UnimplementedChatServiceServer) CreateChat(ctx context.Context, req *Chats) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChat not implemented")
}

func RegisterChatServiceServer(s *grpc.Server, srv ChatServiceServer) {
	s.RegisterService(&_ChatService_serviceDesc, srv)
}

func _ChatService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserContent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gchat.ChatService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).Register(ctx, req.(*UserContent))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserContent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gchat.ChatService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).Login(ctx, req.(*UserContent))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserContent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gchat.ChatService/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).Logout(ctx, req.(*UserContent))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gchat.ChatService/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SendMessage(ctx, req.(*ChatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetChats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RegisterResponse)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServiceServer).GetChats(m, &chatServiceGetChatsServer{stream})
}

type ChatService_GetChatsServer interface {
	Send(*Chats) error
	grpc.ServerStream
}

type chatServiceGetChatsServer struct {
	grpc.ServerStream
}

func (x *chatServiceGetChatsServer) Send(m *Chats) error {
	return x.ServerStream.SendMsg(m)
}

func _ChatService_CreateChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Chats)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).CreateChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gchat.ChatService/CreateChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).CreateChat(ctx, req.(*Chats))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gchat.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _ChatService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _ChatService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _ChatService_Logout_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _ChatService_SendMessage_Handler,
		},
		{
			MethodName: "CreateChat",
			Handler:    _ChatService_CreateChat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetChats",
			Handler:       _ChatService_GetChats_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gchat.proto",
}
