// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gchat.proto

package gchat

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserContent struct {
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserContent) Reset()         { *m = UserContent{} }
func (m *UserContent) String() string { return proto.CompactTextString(m) }
func (*UserContent) ProtoMessage()    {}
func (*UserContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_df1dce88d8f72ba5, []int{0}
}

func (m *UserContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserContent.Unmarshal(m, b)
}
func (m *UserContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserContent.Marshal(b, m, deterministic)
}
func (m *UserContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserContent.Merge(m, src)
}
func (m *UserContent) XXX_Size() int {
	return xxx_messageInfo_UserContent.Size(m)
}
func (m *UserContent) XXX_DiscardUnknown() {
	xxx_messageInfo_UserContent.DiscardUnknown(m)
}

var xxx_messageInfo_UserContent proto.InternalMessageInfo

func (m *UserContent) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserContent) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ChatMessage struct {
	Sequence             int32                `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Message              string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_df1dce88d8f72ba5, []int{1}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetSequence() int32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *ChatMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChatMessage) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type RegisterResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df1dce88d8f72ba5, []int{2}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df1dce88d8f72ba5, []int{3}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df1dce88d8f72ba5, []int{4}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func (m *LogoutResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*UserContent)(nil), "gchat.UserContent")
	proto.RegisterType((*ChatMessage)(nil), "gchat.ChatMessage")
	proto.RegisterType((*RegisterResponse)(nil), "gchat.RegisterResponse")
	proto.RegisterType((*LoginResponse)(nil), "gchat.LoginResponse")
	proto.RegisterType((*LogoutResponse)(nil), "gchat.LogoutResponse")
}

func init() { proto.RegisterFile("gchat.proto", fileDescriptor_df1dce88d8f72ba5) }

var fileDescriptor_df1dce88d8f72ba5 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x57, 0xa5, 0x73, 0x7d, 0x45, 0x91, 0x30, 0xb1, 0xf4, 0xe2, 0x08, 0x28, 0x3d, 0x75,
	0xb0, 0x21, 0xe8, 0x79, 0x78, 0x9b, 0x97, 0xa8, 0x1f, 0x20, 0xab, 0xcf, 0xac, 0x68, 0x93, 0x9a,
	0xa4, 0x7a, 0xf2, 0x5b, 0xf9, 0x01, 0xc5, 0xa4, 0xed, 0xa6, 0x0c, 0x3d, 0xfe, 0x5f, 0x7e, 0x8f,
	0xfc, 0xfe, 0x09, 0xc4, 0xa2, 0x58, 0x73, 0x9b, 0xd7, 0x5a, 0x59, 0x45, 0x42, 0x17, 0xd2, 0x33,
	0xa1, 0x94, 0x78, 0xc1, 0xa9, 0x1b, 0xae, 0x9a, 0xa7, 0xa9, 0x2d, 0x2b, 0x34, 0x96, 0x57, 0xb5,
	0xe7, 0xe8, 0x0d, 0xc4, 0x0f, 0x06, 0xf5, 0x42, 0x49, 0x8b, 0xd2, 0x92, 0x14, 0x46, 0x8d, 0x41,
	0x2d, 0x79, 0x85, 0xc9, 0xde, 0x24, 0xc8, 0x22, 0xd6, 0xe7, 0xef, 0xb3, 0x9a, 0x1b, 0xf3, 0xae,
	0xf4, 0x63, 0xb2, 0xef, 0xcf, 0xba, 0x4c, 0x3f, 0x20, 0x5e, 0xac, 0xb9, 0xbd, 0x45, 0x63, 0xb8,
	0x70, 0xa8, 0xc1, 0xd7, 0x06, 0x65, 0x81, 0x49, 0x30, 0x09, 0xb2, 0x90, 0xf5, 0x99, 0x24, 0x70,
	0x50, 0x79, 0xac, 0xbd, 0xa1, 0x8b, 0xe4, 0x0a, 0xa2, 0x5e, 0xcf, 0xdd, 0x10, 0xcf, 0xd2, 0xdc,
	0x17, 0xc8, 0xbb, 0x02, 0xf9, 0x7d, 0x47, 0xb0, 0x0d, 0x4c, 0x33, 0x38, 0x66, 0x28, 0x4a, 0x63,
	0x51, 0x33, 0x34, 0xb5, 0x92, 0x06, 0xc9, 0x18, 0x42, 0xab, 0x9e, 0x51, 0x3a, 0x81, 0x88, 0xf9,
	0x40, 0xcf, 0xe1, 0x70, 0xa9, 0x44, 0x29, 0xff, 0xc1, 0x2e, 0xe0, 0x68, 0xa9, 0x84, 0x6a, 0xec,
	0xdf, 0xdc, 0xec, 0x33, 0xf0, 0xc5, 0xef, 0x50, 0xbf, 0x95, 0x05, 0x92, 0x6b, 0x18, 0x75, 0x22,
	0x84, 0xe4, 0xfe, 0x43, 0xb6, 0xde, 0x37, 0x3d, 0x6d, 0x67, 0xbf, 0x6d, 0xe9, 0x80, 0xcc, 0x21,
	0x74, 0x66, 0x3b, 0xf7, 0xc6, 0xed, 0xec, 0x87, 0x3b, 0x1d, 0x90, 0x4b, 0x18, 0x7a, 0xcf, 0x9d,
	0x5b, 0x27, 0x9b, 0xad, 0xad, 0x2a, 0x74, 0xb0, 0x1a, 0xba, 0xe7, 0x9c, 0x7f, 0x05, 0x00, 0x00,
	0xff, 0xff, 0x50, 0x06, 0xa9, 0xb8, 0x33, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatServiceClient interface {
	Register(ctx context.Context, in *UserContent, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *UserContent, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *UserContent, opts ...grpc.CallOption) (*LogoutResponse, error)
}

type chatServiceClient struct {
	cc *grpc.ClientConn
}

func NewChatServiceClient(cc *grpc.ClientConn) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) Register(ctx context.Context, in *UserContent, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/gchat.ChatService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) Login(ctx context.Context, in *UserContent, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/gchat.ChatService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) Logout(ctx context.Context, in *UserContent, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/gchat.ChatService/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
type ChatServiceServer interface {
	Register(context.Context, *UserContent) (*RegisterResponse, error)
	Login(context.Context, *UserContent) (*LoginResponse, error)
	Logout(context.Context, *UserContent) (*LogoutResponse, error)
}

// UnimplementedChatServiceServer can be embedded to have forward compatible implementations.
type UnimplementedChatServiceServer struct {
}

func (*UnimplementedChatServiceServer) Register(ctx context.Context, req *UserContent) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedChatServiceServer) Login(ctx context.Context, req *UserContent) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedChatServiceServer) Logout(ctx context.Context, req *UserContent) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}

func RegisterChatServiceServer(s *grpc.Server, srv ChatServiceServer) {
	s.RegisterService(&_ChatService_serviceDesc, srv)
}

func _ChatService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserContent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gchat.ChatService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).Register(ctx, req.(*UserContent))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserContent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gchat.ChatService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).Login(ctx, req.(*UserContent))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserContent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gchat.ChatService/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).Logout(ctx, req.(*UserContent))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gchat.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _ChatService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _ChatService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _ChatService_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gchat.proto",
}
